Feature/changyeop/slack bot
ainize-team/gpu-monitor pull request #4
Opened 2022-05-11 13:42 UTC by scy6500

GPU 가동률을 측정하기 위한 코드입니다.
`utilization_threshold`를 기준하여 GPU의 가동률에 따라 슬랙 메세지를 보내게 됩니다.

2022-05-12 01:04 UTC, byeongal commented
README.md 수정 부탁 드립니다.

2022-05-12 02:18 UTC, scy6500 commented
> README.md 수정 부탁 드립니다.

README.md 업데이트 해두었습니다! 확인 부탁드립니다~

2022-05-13 02:17 UTC, byeongal requested changes

2022-05-13 02:17 UTC, byeongal commented on utils/slack.py
> +    def send_message(self, status: str, server_name: str, utilization: float) -> dict:
dict -> Dict

2022-05-16 07:47 UTC, byeongal approved these changes
LGTM!

2022-05-16 08:08 UTC, merged